version: '3.8'

networks:
  frontend-net: # Rete pubblica
    driver: bridge
  backend-net:  # Rete privata per i dati (DMZ)
    driver: bridge
  control-plane-net: # Rete di gestione (OPA, Splunk)
    driver: bridge

services:

  # 1. IL FIREWALL L3/L4 (NFTables)
  nftables-firewall:
    build: 
      context: ./components/firewall
    container_name: zta-firewall
    cap_add:
      - NET_ADMIN
    networks:
      - frontend-net
      - backend-net

  # 2. LA RISORSA (MongoDB)
  mongodb-resource:
    image: mongo:latest
    container_name: zta-mongodb
    volumes:
      - ./components/dbms/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - backend-net # Isolato, nessuna porta esposta all'host!

  # 3. IL PEP E PROXY (Envoy)
  envoy-pep:
    image: envoyproxy/envoy:v1.30-latest
    container_name: zta-envoy
    volumes:
      - ./components/pep/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./components/pep/lua_script.lua:/etc/envoy/lua_script.lua:ro
      - ./certs:/etc/certs:ro # I certificati per l'mTLS
    depends_on:
      - mongodb-resource
      - opa-pdp
    networks:
      - backend-net
      - control-plane-net

  # 4. L'IDS PASSIVO (Snort)
  snort-ids:
    build: 
      context: ./components/ids
    container_name: zta-snort
    cap_add:
      - NET_ADMIN
    # Si attacca alla scheda di rete di Envoy per ispezionarne il traffico
    network_mode: "service:envoy-pep"

  # 5. IL DECISION MAKER (OPA)
  opa-pdp:
    image: openpolicyagent/opa:latest
    container_name: zta-opa
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policy/rules.rego"
    volumes:
      - ./components/pdp/rules.rego:/policy/rules.rego:ro
    networks:
      - control-plane-net

  # 6. IL SIEM (Splunk)
  splunk-siem:
    image: splunk/splunk:latest
    container_name: zta-splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    ports:
      - "8000:8000" # Web UI
      - "8088:8088" # HEC (HTTP Event Collector per i log)
      - "8089:8089" # API REST
    networks:
      - control-plane-net

  # 7. IL CLIENT DI TEST (Es. Alice)
  client-alice:
    build: 
    context: ./components/clients
    container_name: zta-client-alice
    volumes:
      - ./certs:/etc/certs:ro # Serve il certificato mTLS per bussare a Envoy
    networks:
      - frontend-net