# ACL Basic Setup
acl localnet src 172.20.0.0/24
acl localnet src 172.21.0.0/24

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 3128        # squid proxy

# Definiamo cosa bloccare
acl BadDomains dstdomain .evil-malware-domain.com .suspicious-site.net
acl BadFiles urlpath_regex \.exe$ \.torrent$

# REGOLE Zero Trust L7
http_access deny BadDomains
http_access deny BadFiles
http_access allow localnet
http_access deny all

# Porta di ascolto
http_port 3128

# Impostazioni di log (Che verranno lette da Splunk)
access_log syslog:local1.info squid
